### ISSUE TITLE
Buttons not working inside renderPage component.

### ISSUE THREAD

**Issue by jimmyc1987** [terrysahaidak/react-native-gallery-toolkit#14]
Really cool component, thanks for sharing.

I've run into a problem where `onPress` events aren't called when the button is rendered inside the `renderPage` component in the `StandaloneGallery`. When I tap a button I can see the ripple effect on Android, but the event isn't fired, because of this I can't play videos or download and open files. 

Is this the same problem you experienced [here](https://github.com/terrysahaidak/react-native-gallery-toolkit/blob/master/Example/src/Standalone/FullFeatured.tsx#L340)?

**Comment by terrysahaidak** [comment]
Hi, could you post reproducing example code so I can run it, test, find the problem and fix it?

But probably the problem here is Gesture Handler.
What do you use for buttons?

**Comment by jimmyc1987** [comment]
Ah yes, you were right it was the problem with the Gesture Handler. It works when I use `BaseButton` from `react-native-gesture-handler`. 

Thanks for your help.
